version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: finance_postgres
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_INITDB_ARGS: '--data-checksums --encoding=UTF8 --locale=en_US.UTF-8'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user -d finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: